name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  GO_VERSION: 1.19

jobs:
  # Check if there is any dirty change for go mod tidy
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod

  test-n-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check go mod
        run: |
          go test ./... && go build main.go
